//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public string additional_info { get; set; }
        public string amenities { get; set; }
        public System.DateTime check_in_date { get; set; }
        public System.DateTime check_out_date { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> crawl_date { get; set; }
        public string description { get; set; }
        public string highlight_value { get; set; }
        public Nullable<int> hotel_star_rating { get; set; }
        public Nullable<int> image_count { get; set; }
        public string image_urls { get; set; }
        public string internet { get; set; }
        public string landmark { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public string occupancy { get; set; }
        public string pageurl { get; set; }
        public string property_address { get; set; }
        public int property_id { get; set; }
        public string property_name { get; set; }
        public string property_type { get; set; }
        public string qts { get; set; }
        public string query_time_stamp { get; set; }
        public string room_price { get; set; }
        public string room_types { get; set; }
        public string search_term { get; set; }
        public string service_value { get; set; }
        public string similar_hotel { get; set; }
        public string sitename { get; set; }
        public string things_to_do { get; set; }
        public string things_to_note { get; set; }
        public string uniq_id { get; set; }
    }
}
